### ISSUE TITLE
Power Indicator displays percentage level of main battery

### ISSUE THREAD

**Issue by taniaraven** [elementary/wingpanel-indicator-power#59] opened 2017-10-15 20:28 UTC
My laptop has two batteries, and Elementary displays the 'main' (internal) battery as the percentage in the panel. GNOME displays the average percentage in its quick settings area.

Similarly, the external battery stops discharging at 5% and should probably not display a time remaining estimation as it isn't discharging.

![screenshot from 2017-10-15 21 15 34](https://user-images.githubusercontent.com/29754885/31588829-9a56dd42-b1ef-11e7-85c1-08df30fe6563.png)

My laptop is a Thinkpad X240 if that is of interest.

**Comment by Philip-Scott** [comment] 2017-10-15 21:05
Closing as it's a duplicate of #13 :)

**Closed by Philip-Scott** 2017-10-15 21:05 UTC
