### ISSUE TITLE
Battery Looks Buggy With Mouse Battery

### ISSUE THREAD

**Issue by Fatih20** [elementary/wingpanel-indicator-power#135] opened 2020-04-04 15:35 UTC
## Prerequisites
- [ v] I have searched open and closed issues for duplicates.

## Describe the bug

The battery panel wingpanel is kinda buggy when showing a mouse's battery.
![Screenshot from 2020-04-04 22-10-10](https://user-images.githubusercontent.com/51940383/78454647-9f356b80-76c3-11ea-9ef7-9de41eaa8d80.png)
![Screenshot from 2020-04-04 22-10-01](https://user-images.githubusercontent.com/51940383/78454648-a0ff2f00-76c3-11ea-899e-87075550e42d.png)
The symbolic battery icon should've been full and the percentage shouldn't have been 0 percent.

### To Reproduce
1. Go to your desktop
2. Plug a wireless mouse
3. Check the panel

## Platform Information
![System Info](https://user-images.githubusercontent.com/51940383/78454810-9729fb80-76c4-11ea-8901-baf881c2cf59.png)

Please check what applies:
-->
- [ ] I'm using the latest version from git that I've manually compiled
- [ v] I'm using the latest released stable version

**Comment by kvdz** [comment] 2020-11-30 21:06
@Fatih20 Thank you for repoting this bug,  could you give me some more internal information by executing this command in the terminal.
`upower -d`

**Comment by kvdz** [comment] 2020-12-03 20:37
My personal desktop shows it like this:  

```
upower -d
Device: /org/freedesktop/UPower/devices/line_power_AC
  native-path:          AC
  power supply:         yes
  updated:              di 01 dec 2020 21:12:25 CET (37 seconds ago)
  has history:          no
  has statistics:       no
  line-power
    warning-level:       none
    online:              yes
    icon-name:          'ac-adapter-symbolic'

Device: /org/freedesktop/UPower/devices/DisplayDevice
  power supply:         no
  updated:              di 01 dec 2020 21:12:21 CET (41 seconds ago)
  has history:          no
  has statistics:       no
  unknown
    warning-level:       none
    icon-name:          'battery-missing-symbolic'

Daemon:
  daemon-version:  0.99.7
  on-battery:      no
  lid-is-closed:   no
  lid-is-present:  no
  critical-action: HybridSleep
```

I don't have a wireless mouse, so I don't see the indicator.

**Comment by danirabbit** [comment] 2024-08-30 01:52
I can't reproduce this issue and we never got more information from the OP, so closing as "incomplete"

**Closed by danirabbit** 2024-08-30 01:52 UTC
