### ISSUE TITLE
Icon should show actual battery level

### ISSUE THREAD

**Issue by hanaral** [elementary/wingpanel-indicator-power#162] opened 2021-01-25 01:24 UTC
## Problem

The fd.o spec only supports empty, caution,  low, good and full. These obviously don't paint a full picture without having to enable the percentage or click on the indicator.

## Proposal

Maybe use an empty icon with css to adjust the "fill" inside it (I'm really not sure what the limits of CSS magic are). Maybe it would be better not to have complete spec-for-spec compliance here since I cannot see any harm in doing so, maybe there could be 'slices' of battery levels (in increments of 5% or 10%?), and the indicator could slowly fade through them.

## Prior Art

![macbook_battery_indicator](https://user-images.githubusercontent.com/58219504/105650489-ca37b880-5eab-11eb-9276-2c5a4de78fed.jpeg)

**Comment by kvdz** [comment] 2021-03-22 19:58
Hi Hanaral, Thank you for taking the time to write this feature request.

I personally like you view. I am unaware of CSS could achieve this but i guess we can find out.  For now i have put it on the wishlist as first assesment.

**Comment by andirsun** [comment] 2021-05-09 22:44
> Hi Hanaral, Thank you for taking the time to write this feature request.
> 
> I personally like you view. I am unaware of CSS could achieve this but i guess we can find out. For now i have put it on the wishlist as first assesment.

Would be a possible solution, create icons for custom percentages like every 5% (0%, 5%, 10%, 15% etc)

**Comment by danirabbit** [comment] 2024-08-14 21:49
Gonna close this as duplicate of #257 since I have a bit more info there about the icon spec etc

**Closed by danirabbit** 2024-08-14 21:49 UTC
Labels: Priority: Wishlist
