### ISSUE TITLE
(Mouse) Power indicator not shown

### ISSUE THREAD

**Issue by jongmana** [elementary/wingpanel-indicator-power#55] opened 2017-08-15 12:38 UTC
My Desktop PC doesn't run on Battery, but the mouse I use does.
The battery icon for the mouse is only shown on the lock-screen (and the percentage keeps on calculating)
After I logged in the indicator is gone, and cannot be restored via the settings.
Guess that this is a feature?

**Comment by fabianthoma** [comment] 2018-02-04 17:09
Could you run `upower --dump` in a terminal and post the output here? That way we can get a better idea about the types of devices that get reported by upower, which is where the indicator gets it's data from.

Intended behaviour would be not showing the indicator as long as there are no battery devices. So on a desktop it would only show up when there is a device with a battery present. Not exactly sure what icon it would display then though.

**Comment by danrabbit** [comment] 2018-06-21 16:41
Closing as "Incomplete" since OP never followed up with more info. Please feel free to reopen if you have more info to report

**Closed by danrabbit** 2018-06-21 16:41 UTC
Labels: Status: Incomplete
